<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UB6TGO0" failures="1" tests="3" name="app test 2" time="0.053" errors="0" timestamp="2022-12-08T19:08:48 PST">
  <testcase classname="testngclass.TestReporterTest" name="Test2" time="0.008">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at testngclass.TestReporterTest.Test2(TestReporterTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="testngclass.TestReporterTest" name="Test1" time="0.001"/>
  <testcase classname="testngclass.TestReporterTest" name="Test3" time="0.0">
    <skipped/>
  </testcase> <!-- Test3 -->
</testsuite> <!-- app test 2 -->
